<a href="https://colab.research.google.com/github/ark150/PracticaSIDI2Semana1/blob/master/SistDist2_Semana_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#

In [0]:
import numpy as np
a = np.random.rand(10000)

In [4]:
a.shape

(10000,)

In [5]:
a.dtype

dtype('float64')

In [6]:
a.nbytes

80000

In [8]:
%time a.sum()

CPU times: user 458 µs, sys: 60 µs, total: 518 µs
Wall time: 462 µs


4994.7113528091895

In [0]:
import dask.array as da

In [0]:
a_dask = da.from_array(a, chunks=len(a)//3)

In [12]:
type(a_dask)

dask.array.core.Array

In [13]:
a_dask.chunks

((3333, 3333, 3333, 1),)

In [0]:
n_chunks = 8
chunks_size = len(a) // n_chunks
res = 0

time con 2 % es para toda las lineas que se ejecutan

time con un % es para una linea y tiene que estar junto de esa linea

In [19]:
%%time
for k in range (n_chunks):
  offset = k*chunks_size
  a_chunks = a[offset:offset + chunks_size]
  res += a_chunks.sum()

CPU times: user 221 µs, sys: 53 µs, total: 274 µs
Wall time: 207 µs


In [20]:
%time res_dask = a_dask.sum()

CPU times: user 188 µs, sys: 1.05 ms, total: 1.24 ms
Wall time: 1.24 ms


In [22]:
%time res_dask.compute()

CPU times: user 2.51 ms, sys: 2.9 ms, total: 5.4 ms
Wall time: 5.7 ms


4994.7113528091895

In [0]:
res_dask.visualize(rankdir='LR')

##ejercicio 

redefinir el arreglo a_dask usando trozos equivalentes a los usados en el for y comparar tiempos de ejecucion

Discutir lo obtenido

#medir tiempos de operacion sobre arreglos con dask

In [24]:
!wget https://www.gw-osc.org/archive/data/S5/814743552/H-H1_LOSC_4_V1-815411200-4096.hdf5

--2019-05-28 15:57:07--  https://www.gw-osc.org/archive/data/S5/814743552/H-H1_LOSC_4_V1-815411200-4096.hdf5
Resolving www.gw-osc.org (www.gw-osc.org)... 131.215.125.179
Connecting to www.gw-osc.org (www.gw-osc.org)|131.215.125.179|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.gw-openscience.org/archive/data/S5/814743552/H-H1_LOSC_4_V1-815411200-4096.hdf5 [following]
--2019-05-28 15:57:08--  https://www.gw-openscience.org/archive/data/S5/814743552/H-H1_LOSC_4_V1-815411200-4096.hdf5
Resolving www.gw-openscience.org (www.gw-openscience.org)... 131.215.125.179
Connecting to www.gw-openscience.org (www.gw-openscience.org)|131.215.125.179|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /archive/data/S5/814743552/H-H1_LOSC_4_V1-815411200-4096.hdf5/ [following]
--2019-05-28 15:57:09--  https://www.gw-openscience.org/archive/data/S5/814743552/H-H1_LOSC_4_V1-815411200-4096.hdf5/
Reusing existing connection t

In [0]:
!cp H-H1_LOSC_4_V1-815411200-4096.hdf5 LIGO_data.hdf5

In [0]:
import h5py, time

In [27]:
datos = h5py.File('./LIGO_data.hdf5')
type(datos)

h5py._hl.files.File

In [29]:
for key in datos.keys():
  print(key)

meta
quality
strain


In [0]:
with datos as dset:
  strain = dset['strain']['Strain'][:]

In [32]:
strain

array([-2.37884722e-16, -2.55453801e-16, -2.72831053e-16, ...,
                   nan,             nan,             nan])

In [34]:
type(strain)

numpy.ndarray

In [35]:
strain.shape

(16777216,)

nan = no a number

In [39]:
strain.sum()

nan

dividir los chunsk de la linea de abajo usando 2,4,8,16,32,64,128

In [0]:
strain_dask8 = da.from_array(strain, chunks = strain.shape[0]//8)

In [45]:
ti = time.time()
promedio8 = strain_dask8.mean().compute()
tf = time.time()
print('Tiempo transcurrido: {} ms'.format((tf-ti)*1000))

Tiempo transcurrido: 76.18045806884766 ms


In [44]:
print(promedio8)

nan


In [0]:
strain_dask8.visualize()

#arreglos numpy mutidimensionales

In [0]:
ts = np.array([49,51,60,54,47,50,64,58,47,43,50,63,67,68,64,48,55,46,66,51,52])
np.savetxt('temp_max.csv', ts.astype(int), fmt='%i')

In [48]:
ls

H-H1_LOSC_4_V1-815411200-4096.hdf5  mydask.png    temp_max.csv
LIGO_data.hdf5                      sample_data/


In [0]:
!cat temp_max.csv

In [50]:
ts = np.loadtxt('temp_max.csv', dtype=np.int64)
type(ts)

numpy.ndarray

In [51]:
ts.shape

(21,)

In [52]:
ts.ndim

1

In [53]:
print(ts)

[49 51 60 54 47 50 64 58 47 43 50 63 67 68 64 48 55 46 66 51 52]


In [54]:
ts.mean()

54.904761904761905

In [56]:
ts.std()

7.63391406756257

In [77]:
mier =[]
for i,v in enumerate(ts):
  if i%7==2:
    mier.append(v)
print(mier)
np.mean(mier)

[60, 43, 55]


52.666666666666664

In [0]:
semanas = ts.reshape([3,7])

In [81]:
type(semanas)

numpy.ndarray

In [84]:
semanas.ndim

2

In [86]:
semanas.size

21

In [89]:
semanas

array([[49, 51, 60, 54, 47, 50, 64],
       [58, 47, 43, 50, 63, 67, 68],
       [64, 48, 55, 46, 66, 51, 52]])

In [95]:
semanas[:,3].mean()

50.0

In [96]:
semanas[2,:].mean()

54.57142857142857

In [101]:
semanas[:,3:6]

array([[54, 47, 50],
       [50, 63, 67],
       [46, 66, 51]])

In [103]:
ts.reshape([7,3], order='F')

array([[49, 58, 64],
       [51, 47, 48],
       [60, 43, 55],
       [54, 50, 46],
       [47, 63, 66],
       [50, 67, 51],
       [64, 68, 52]])

In [0]:
dias=semanas.transpose()

In [107]:
dias[4,:]

array([47, 63, 66])

In [108]:
dias

array([[49, 58, 64],
       [51, 47, 48],
       [60, 43, 55],
       [54, 50, 46],
       [47, 63, 66],
       [50, 67, 51],
       [64, 68, 52]])

In [114]:
dias.mean(axis=1)

array([57.        , 48.66666667, 52.66666667, 50.        , 58.66666667,
       56.        , 61.33333333])

In [119]:
asd=semanas - dias.mean(axis=1)
asd.transpose()

array([[ -8.        ,   1.        ,   7.        ],
       [  2.33333333,  -1.66666667,  -0.66666667],
       [  7.33333333,  -9.66666667,   2.33333333],
       [  4.        ,   0.        ,  -4.        ],
       [-11.66666667,   4.33333333,   7.33333333],
       [ -6.        ,  11.        ,  -5.        ],
       [  2.66666667,   6.66666667,  -9.33333333]])

In [0]:
tabla= dias-dias.mean(axis=0)

In [123]:
tabla

array([[ -4.57142857,   1.42857143,   9.42857143],
       [ -2.57142857,  -9.57142857,  -6.57142857],
       [  6.42857143, -13.57142857,   0.42857143],
       [  0.42857143,  -6.57142857,  -8.57142857],
       [ -6.57142857,   6.42857143,  11.42857143],
       [ -3.57142857,  10.42857143,  -3.57142857],
       [ 10.42857143,  11.42857143,  -2.57142857]])

In [125]:
tabla.reshape([3,7])

array([[ -4.57142857,   1.42857143,   9.42857143,  -2.57142857,
         -9.57142857,  -6.57142857,   6.42857143],
       [-13.57142857,   0.42857143,   0.42857143,  -6.57142857,
         -8.57142857,  -6.57142857,   6.42857143],
       [ 11.42857143,  -3.57142857,  10.42857143,  -3.57142857,
         10.42857143,  11.42857143,  -2.57142857]])

#como se usa esto con dask

In [0]:
data=np.genfromtxt('https://www1.ncdc.noaa.gov/pub/data/ccd-data/hghtmp15.dat', usecols=(2,3,4,5),skip_header=5, dtype=np.int64)

In [130]:
data.shape

(259, 4)

In [131]:
type(data)

numpy.ndarray

In [0]:
data_dask = da.from_array(data, chunks=(259,2))

In [0]:
res = data_dask.mean(axis=0)

In [0]:
res.visualize(rankdir='LR')

In [137]:
res.compute()

array([51.83011583, 71.91891892, 80.93050193, 89.22007722])

El anterior es lo mismo que

In [134]:
data.mean(axis=0)

array([51.83011583, 71.91891892, 80.93050193, 89.22007722])

#tarea

leer como un archivo de dask array
